#!/bin/bash

#test if the service is up
if [[ -z "$DBHOST" ]]; then
  DBHOST="mysql"
fi

if [[ -z "$DBCHECK" ]]; then
  SERVICE_ADDR=$DBHOST
  SERVICE_PORT=3306
  CONN_STATUS="DOWN"
  COUNTER=0
  while [ "$CONN_STATUS" == "DOWN" -a $COUNTER -lt 4 ]
  do
    CONN_STATUS=`(echo > /dev/tcp/$SERVICE_ADDR/$SERVICE_PORT) >/dev/null 2>&1 && echo "UP" || echo "DOWN"`
    echo -e "\t $DBHOST connection status: $CONN_STATUS"
    echo -e "\t waiting 5s for $DBHOST connection..."
    sleep 5
    let COUNTER=COUNTER+1
  done
fi

if [[ -z "$WP_DEBUG" ]]; then
  WP_DEBUG=false
fi

if [[ -z "$ENV" ]]; then
  ENV='production'
fi

if [[ -z "$IS_HTTPS" ]]; then
  PROTOCOL='http'
  SERVER_HTTPS='off'
else
  PROTOCOL='https'
  SERVER_HTTPS='on'
fi

CONFIG=$(cat <<PHP
define( 'DISALLOW_FILE_EDIT', true );
define( 'WP_CONTENT_DIR', \$_SERVER['DOCUMENT_ROOT'] . '/wp-content' );
define( 'WP_PLUGIN_DIR', \$_SERVER['DOCUMENT_ROOT'] . '/wp-content/plugins' );
define( 'PLUGINDIR', \$_SERVER['DOCUMENT_ROOT'] . '/wp-content/plugins' );

define( 'WP_SITEURL', '${PROTOCOL}://' . \$_SERVER['HTTP_HOST'] . '/');
define( 'WP_HOME',    '${PROTOCOL}://' . \$_SERVER['HTTP_HOST'] . '/');
define( 'WP_CONTENT_URL', '${PROTOCOL}://' . \$_SERVER['HTTP_HOST'] . '/wp-content');
define( 'WP_PLUGIN_URL',  '${PROTOCOL}://' . \$_SERVER['HTTP_HOST'] . '/wp-content/plugins');
define( 'UPLOADS',  'wp-content/uploads' );
define( 'WP_DEBUG', $WP_DEBUG );
define( 'ENV', '$ENV' );
\$_SERVER['HTTPS'] = '$SERVER_HTTPS';
PHP
)

#additional wp-config settings
if [[ -f "/wp-config" ]]; then
  echo "Including additional settings from wp-config and skipping salt generation"
  USER_CONFIG="$(cat /wp-config)"
  SKIPSALT=true
fi

CONFIG=$(cat <<PHP
$CONFIG
$USER_CONFIG
PHP
)

#reset wp-config.php
rm -f wp-config.php
wp --allow-root config create \
  --dbhost=$DBHOST \
  --dbname=$DBNAME \
  --dbuser=$DBUSER \
  --dbpass=$DBPASS \
  --skip-salts=$SKIPSALT \
  --extra-php <<PHP
$CONFIG
PHP

if ! $(wp --allow-root core is-installed); then
  echo "creating database"
  wp --allow-root db create
  echo "installing wordpress..."
  wp --allow-root core install \
    --url="$WORDPRESS_URL" \
    --title="$WORDPRESS_TITLE" \
    --admin_email="$WORDPRESS_ADMIN_EMAIL" \
    --admin_name="$WORDPRESS_ADMIN_NAME" \
    --admin_password="$WORDPRESS_ADMIN_PASS"
fi

if [[ -n "$THEME" ]]; then
  wp --allow-root theme activate $THEME
fi
wp --allow-root rewrite structure '/%postname%/'

if [[ -f "/setup-after" ]]; then
  bash /setup-after
fi

exec $@
